### PR TITLE
modified CameraDepth_sensor_fixedjoint z value to fit rgb image and depth image

### PR DESCRIPTION
**Pull request by kochigami**
I modified z value of CameraDepth_sensor_fixedjoint to fit rgb (```pepper_robot/camera/front/image_raw```) and depth image (```pepper_robot/camera/depth/image_raw```) of pepper.
I modified z value just by my eyes. 
I'd like to have a review on this.

pepper's pointcloud view before modified z value
before_modified_joint_z_value

```
rosrun tf tf_echo CameraTop_optical_frame CameraDepth_optical_frame 10

At time 1465464133.728
- Translation: [0.039, 0.044, 0.035]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
            in RPY (radian) [0.000, -0.000, 0.000]
            in RPY (degree) [0.000, -0.000, 0.000]
```
I used this program to publish pepper's pointcloud.
```
<launch>
  <node pkg="tf" name="depth_to_top_camera_frame_publisher" type="static_transform_publisher" args="0.039 0.044 0.035 0.000 0.000 0.000 CameraTop_optical_frame CameraDepth_optical_frame 1"/>
  <node pkg="image_proc" type="image_proc" name="rgb_processing" output="screen" ns="/pepper_robot/camera/front">
  </node>

  <node pkg="nodelet" type="nodelet" name="register_depth" output="screen"
        args="standalone depth_image_proc/register" >
    <remap from="rgb/camera_info" to="/pepper_robot/camera/front/camera_info"/>
    <remap from="depth/camera_info" to="/pepper_robot/camera/depth/camera_info"/>
    <remap from="depth/image_rect" to="/pepper_robot/camera/depth/image_raw"/>
    <remap from="depth_registered/camera_info" to="/pepper_robot/camera/depth_registered/camera_info"/>
    <remap from="depth_registered/image_rect" to="/pepper_robot/camera/depth_registered/image_rect"/>
  </node>

  <node pkg="nodelet" type="nodelet" name="cloudify" output="screen"
        args="standalone depth_image_proc/point_cloud_xyzrgb" >
    <remap from="rgb/camera_info" to="/pepper_robot/camera/front/camera_info"/>
    <remap from="rgb/image_rect_color" to="/pepper_robot/camera/front/image_rect_color"/>
    <remap from="depth_registered/image_rect" to="/pepper_robot/camera/depth_registered/image_rect"/>
    <remap from="depth_registered/points" to="/pepper_robot/camera/depth/points"/>
  </node>
</launch>
```

pepper's pointcloud view after I modified z value
after_modified_joint_z_value

```
rosrun tf tf_echo CameraTop_optical_frame CameraDepth_optical_frame 10

At time 1465463676.955
- Translation: [0.039, 0.074, 0.035]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
            in RPY (radian) [0.000, -0.000, 0.000]
            in RPY (degree) [0.000, -0.000, 0.000]
```
I used this program to publish pepper's pointcloud. 
What I changed is only
```
 <node pkg="tf" name="depth_to_top_camera_frame_publisher" type="static_transform_publisher" args="0.039 0.074 0.035 0.000 0.000 0.000 CameraTop_optical_frame CameraDepth_optical_frame 1"/>
```

```
<launch>
  <node pkg="tf" name="depth_to_top_camera_frame_publisher" type="static_transform_publisher" args="0.039 0.074 0.035 0.000 0.000 0.000 CameraTop_optical_frame CameraDepth_optical_frame 1"/>
  <node pkg="image_proc" type="image_proc" name="rgb_processing" output="screen" ns="/pepper_robot/camera/front">
  </node>

  <node pkg="nodelet" type="nodelet" name="register_depth" output="screen"
        args="standalone depth_image_proc/register" >
    <remap from="rgb/camera_info" to="/pepper_robot/camera/front/camera_info"/>
    <remap from="depth/camera_info" to="/pepper_robot/camera/depth/camera_info"/>
    <remap from="depth/image_rect" to="/pepper_robot/camera/depth/image_raw"/>
    <remap from="depth_registered/camera_info" to="/pepper_robot/camera/depth_registered/camera_info"/>
    <remap from="depth_registered/image_rect" to="/pepper_robot/camera/depth_registered/image_rect"/>
  </node>

  <node pkg="nodelet" type="nodelet" name="cloudify" output="screen"
        args="standalone depth_image_proc/point_cloud_xyzrgb" >
    <remap from="rgb/camera_info" to="/pepper_robot/camera/front/camera_info"/>
    <remap from="rgb/image_rect_color" to="/pepper_robot/camera/front/image_rect_color"/>
    <remap from="depth_registered/image_rect" to="/pepper_robot/camera/depth_registered/image_rect"/>
    <remap from="depth_registered/points" to="/pepper_robot/camera/depth/points"/>
  </node>
</launch>
```

### CODE REVIEW

**Comment by k-okada** [comment]
Nice!
How many papers did you check if this parameters are correct. Please check
at least two ;-)

2016年6月9日木曜日、Kanae Kochigami<notifications@github.com>さんは書きました:

> I modified z value of CameraDepth_sensor_fixedjoint to fit rgb (
> pepper_robot/camera/front/image_raw) and depth image (
> pepper_robot/camera/depth/image_raw) of pepper.
> I modified z value just by my eyes.
> I'd like to have a review on this.
>
> before modified z value
> [image: before_modified_joint_z_value]
> <https://cloud.githubusercontent.com/assets/7259671/15924750/acd9280e-2e6e-11e6-9bec-8a33971ae944.png>
>
> rosrun tf tf_echo CameraTop_optical_frame CameraDepth_optical_frame 10
>
> At time 1465464133.728
> - Translation: [0.039, 0.044, 0.035]
> - Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
>             in RPY (radian) [0.000, -0.000, 0.000]
>             in RPY (degree) [0.000, -0.000, 0.000]
>
> I used this program to publish pepper's pointcloud.
>
> <launch>
>   <node pkg="tf" name="depth_to_top_camera_frame_publisher" type="static_transform_publisher" args="0.039 0.044 0.035 0.000 0.000 0.000 CameraTop_optical_frame CameraDepth_optical_frame 1"/>
>   <node pkg="image_proc" type="image_proc" name="rgb_processing" output="screen" ns="/pepper_robot/camera/front">
>   </node>
>
>   <node pkg="nodelet" type="nodelet" name="register_depth" output="screen"
>         args="standalone depth_image_proc/register" >
>     <remap from="rgb/camera_info" to="/pepper_robot/camera/front/camera_info"/>
>     <remap from="depth/camera_info" to="/pepper_robot/camera/depth/camera_info"/>
>     <remap from="depth/image_rect" to="/pepper_robot/camera/depth/image_raw"/>
>     <remap from="depth_registered/camera_info" to="/pepper_robot/camera/depth_registered/camera_info"/>
>     <remap from="depth_registered/image_rect" to="/pepper_robot/camera/depth_registered/image_rect"/>
>   </node>
>
>   <node pkg="nodelet" type="nodelet" name="cloudify" output="screen"
>         args="standalone depth_image_proc/point_cloud_xyzrgb" >
>     <remap from="rgb/camera_info" to="/pepper_robot/camera/front/camera_info"/>
>     <remap from="rgb/image_rect_color" to="/pepper_robot/camera/front/image_rect_color"/>
>     <remap from="depth_registered/image_rect" to="/pepper_robot/camera/depth_registered/image_rect"/>
>     <remap from="depth_registered/points" to="/pepper_robot/camera/depth/points"/>
>   </node>
> </launch>
>
> [image: after_modified_joint_z_value]
> <https://cloud.githubusercontent.com/assets/7259671/15924586/cf2e5f24-2e6d-11e6-839b-9b9f49b5ab55.png>
>
> rosrun tf tf_echo CameraTop_optical_frame CameraDepth_optical_frame 10
>
> At time 1465463676.955
> - Translation: [0.039, 0.074, 0.035]
> - Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
>             in RPY (radian) [0.000, -0.000, 0.000]
>             in RPY (degree) [0.000, -0.000, 0.000]
>
> I used this program to publish pepper's pointcloud.
> What I changed is only
>
>  <node pkg="tf" name="depth_to_top_camera_frame_publisher" type="static_transform_publisher" args="0.039 0.074 0.035 0.000 0.000 0.000 CameraTop_optical_frame CameraDepth_optical_frame 1"/>
>
> <launch>
>   <node pkg="tf" name="depth_to_top_camera_frame_publisher" type="static_transform_publisher" args="0.039 0.074 0.035 0.000 0.000 0.000 CameraTop_optical_frame CameraDepth_optical_frame 1"/>
>   <node pkg="image_proc" type="image_proc" name="rgb_processing" output="screen" ns="/pepper_robot/camera/front">
>   </node>
>
>   <node pkg="nodelet" type="nodelet" name="register_depth" output="screen"
>         args="standalone depth_image_proc/register" >
>     <remap from="rgb/camera_info" to="/pepper_robot/camera/front/camera_info"/>
>     <remap from="depth/camera_info" to="/pepper_robot/camera/depth/camera_info"/>
>     <remap from="depth/image_rect" to="/pepper_robot/camera/depth/image_raw"/>
>     <remap from="depth_registered/camera_info" to="/pepper_robot/camera/depth_registered/camera_info"/>
>     <remap from="depth_registered/image_rect" to="/pepper_robot/camera/depth_registered/image_rect"/>
>   </node>
>
>   <node pkg="nodelet" type="nodelet" name="cloudify" output="screen"
>         args="standalone depth_image_proc/point_cloud_xyzrgb" >
>     <remap from="rgb/camera_info" to="/pepper_robot/camera/front/camera_info"/>
>     <remap from="rgb/image_rect_color" to="/pepper_robot/camera/front/image_rect_color"/>
>     <remap from="depth_registered/image_rect" to="/pepper_robot/camera/depth_registered/image_rect"/>
>     <remap from="depth_registered/points" to="/pepper_robot/camera/depth/points"/>
>   </node>
> </launch>
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ros-naoqi/naoqi_driver/pull/71
> Commit Summary
>
>    - modified CameraDepth_sensor_fixedjoint z value to fit rgb image and
>    depth image
>
> File Changes
>
>    - *M* share/urdf/pepper.urdf
>    <https://github.com/ros-naoqi/naoqi_driver/pull/71/files#diff-0> (2)
>
> Patch Links:
>
>    - https://github.com/ros-naoqi/naoqi_driver/pull/71.patch
>    - https://github.com/ros-naoqi/naoqi_driver/pull/71.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros-naoqi/naoqi_driver/pull/71>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3EfDqEWW4eK_q8oOvkJv7LPAFLbjks5qJ91TgaJpZM4IxyUW>
> .
>


-- 
--
◉ Kei Okada

**Comment by suryaambrose** [comment]
That looks nice !!

1) As @k-okada said, please check that your new value is better than the old one on at least two different setups, just to make sure this is a good "general" value. 
2) If we want to change this value, the process might be a little more tricky. AFAIK, urdf are generated, so it would make more sense to change the original files instead of the ones stored here (or the next urdf generation would erase your change). @mikaelarguedas , you can give much better clues than me here, what would be the best choice ?

**Comment by kochigami** [comment]
@k-okada  @suryaambrose 

Thank you very much for your advice.
I'll check this with different situations.

**Comment by nlyubova** [comment]
It is better to update URDF in https://github.com/ros-naoqi/pepper_robot/blob/master/pepper_description/urdf/pepper1.0_generated_urdf/pepper_sensors.xacro

**Comment by kochigami** [comment]
@nlyubova 
Thank you very much for your help.
I'll close this issue and send a new pull-request to pepper_robot.

**Comment by nlyubova** [comment]
great!

**Comment by mikaelarguedas** [comment]
Sorry for the delay. 
@kochigami How many peppers do you have at your disposal for testing ?
We experience inconsistency in depth measurement from one pepper to the next due to the lenses in front of the 3D sensor. It would be great to validate this change on several robots with different setups (different distances like 1m and 3m).
@suryaambrose @nlyubova It would be great to confirm inhouse if the position of the sensor provided in the URDF is the one used for manufacturing. If not it would make more sense to push the change in naoqi libraries and it will propagate automatically to the URDFs when generated.

**Comment by kochigami** [comment]
I found that the pointcloud generated by the combination of rgb and depth image is varied from one Pepper to another...
I felt it is difficult to find the correct value for all Pepper. 
I gave up sending a pull-request for it. Sorry for my trouble.

These photos below are about the trial of this pull-request change with two Pepper. 
The distance between the table and Pepper is about 60 cm.

one pepper 
cinnamon_pull_request
another pepper
olive_pull_request

In ```naoqi_driver```, pepper.urdf is directly loaded from ```naoqi_driver/share/urdf/pepper.urdf```. (https://github.com/ros-naoqi/naoqi_driver/blob/master/src/helpers/filesystem_helpers.hpp#L112)
I think it is more convenient if we can set xacro of urdf as a parameter ```robot_description``` when launching ```naoqi_driver.launch``` .

**Comment by nlyubova** [comment]
hello, I have just tested this PR on three Peppers (rather new version) and I've found out that RGB and depth are not aligned neither with this PR nor without. It seems that aligning RGB with depth at one part of the image (top, for example) makes it worse in another part (bottom).  There is also problems in Y in addition to Z axis. So it could be a problem in the camera's orientation in addition to position.

**Comment by k-okada** [comment]
I believe @furushchev is working on automated program for registration problem.

**Comment by lahiruherath** [comment]
Hi,

Did anyone find a proper solution for this?

**Pull request closed without merging**
