### PR TITLE
Fix broken compilation with libqi-2.5

### PR DESCRIPTION
**Pull request by suryaambrose**

### CODE REVIEW

**Comment by suryaambrose** [comment]
@severin-lemaignan  this commit basically does the same thing as you, but makes it possible at the same time to use libqi 2.3 (cf https://github.com/ros-naoqi/libqi-release/issues/3). I just forgot to add your -std=gnu++11 addition, how important is it ?

**Comment by k-okada** [comment]
Hi, the patch seems ok to me, but I can not compile this on indigo,  since ros-indigo-naoqi-libqicore is staill 2.3.1, i think. 
```
[naoqi_driver] /usr/bin/c++   -DCATKIN_BUILD -DLIBQI_VERSION=25 -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"naoqi_driver\" -Dnaoqi_driver_EXPORTS -std=gnu++11 -Werror=deprecated-declarations -fPIC -I/usr/include/opencv -I/home/k-okada/catkin_ws/ws_naoqi/src/naoqi_driver/include -I/opt/ros/indigo/include -I/usr/include/eigen3    -o CMakeFiles/naoqi_driver.dir/src/publishers/log.cpp.o -c /home/k-okada/catkin_ws/ws_naoqi/src/naoqi_driver/src/publishers/log.cpp 
[naoqi_driver] In file included from /opt/ros/indigo/include/qi/anyfunction.hpp:53:0,                                                
[naoqi_driver]                  from /opt/ros/indigo/include/qi/signal.hpp:12,                                                       
[naoqi_driver]                  from /opt/ros/indigo/include/qi/anyobject.hpp:15,                                                    
[naoqi_driver]                  from /home/k-okada/catkin_ws/ws_naoqi/src/naoqi_driver/include/naoqi_driver/tools.hpp:30,            
[naoqi_driver]                  from /home/k-okada/catkin_ws/ws_naoqi/src/naoqi_driver/src/converters/converter_base.hpp:24,         
[naoqi_driver]                  from /home/k-okada/catkin_ws/ws_naoqi/src/naoqi_driver/src/converters/log.hpp:24,                    
[naoqi_driver]                  from /home/k-okada/catkin_ws/ws_naoqi/src/naoqi_driver/src/converters/log.cpp:18:                    
[naoqi_driver] /opt/ros/indigo/include/qi/type/typeinterface.hpp:396:51: error: QI_TYPE_ENUM_REGISTER_ is deprecated (declared at /opt/ros/indigo/include/qi/type/typeinterface.hpp:387) [-Werror=deprecated-declarations] 
[naoqi_driver]        static const detail::QI_TYPE_ENUM_REGISTER_ BLAH;              \                                               
[naoqi_driver]                                                    ^                                                                  
[naoqi_driver] /opt/ros/indigo/include/qicore/logmessage.hpp:15:1: note: in expansion of macro QI_TYPE_ENUM_REGISTER                 
[naoqi_driver]  QI_TYPE_ENUM_REGISTER(qi::LogLevel)                   
```

**Comment by k-okada** [comment]
Oh, this is already ticketed at https://github.com/ros-naoqi/libqicore-release/pull/1

**Comment by suryaambrose** [comment]
Yes, and those fixes are already pushed actually, but I forgot to update the distribution.yaml file in rosdistro which is why libqicore can still not compile. It is done now, so the package should be updated soon.

**Comment by suryaambrose** [comment]
But anyway, naoqi_driver will not compile until I fixed this https://github.com/ros-naoqi/libqi-release/issues/3

**Pull request merged**
