### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by Pandhariix**
Add Travis CI, build naoqi driver with 
* Indigo
* Jade
* Kinetic
* Lunar

Create a custom display of the CI results in the README

### CODE REVIEW

**Comment by nlyubova** [comment]
Could you please add a line explaining the table, like "Travis - Continuous Integration" to the README ?

**Comment by Pandhariix** [comment]
Sure, done

**Comment by Pandhariix** [comment]
I also restricted the CI to the master branch of the project

**Comment by mikaelarguedas** [comment]
[Jade is EOL](https://discourse.ros.org/t/jade-eol-announcement/2240) so I would recommend not testing it in travis as it's not possible to release new code for it anymore

**Comment by nlyubova** [comment]
@Pandhariix could you please remove Jade from your Travis check and make a new PR?

**Comment by nlyubova** [comment]
@mikaelarguedas thank you for your notice!

**Pull request merged**
